-- Baseline migration — entries, entries_versions, chunks, audit_log.
-- Generated by drizzle-kit from drizzle/schema.ts; see ADR-0008 + ADR-0009.
-- pgvector extension is installed by db/init.sql at first-volume-init (ADR-0008 §10);
-- migrations run as the app user and do not (and must not) own CREATE EXTENSION.
-- Future HNSW indexes built against a populated table must ship in their own
-- no-other-DDL migration using CREATE INDEX CONCURRENTLY (ADR-0008 §12).
CREATE TABLE IF NOT EXISTS "audit_log" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"kind" text NOT NULL,
	"entry_id" uuid,
	"prompt_hash" text,
	"payload" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "audit_log_prompt_hash_required_for_agent" CHECK ("audit_log"."kind" NOT LIKE 'agent_%' OR "audit_log"."prompt_hash" IS NOT NULL)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "chunks" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"entry_id" uuid NOT NULL,
	"sensitivity" text NOT NULL,
	"chunk_index" integer NOT NULL,
	"chunk_total" integer NOT NULL,
	"content_start" integer NOT NULL,
	"content_end" integer NOT NULL,
	"token_count" integer NOT NULL,
	"chunking_policy_version" text NOT NULL,
	"embedding" vector(1024) NOT NULL,
	"embedding_model" text NOT NULL,
	"embedding_version" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "chunks_sensitivity_check" CHECK ("chunks"."sensitivity" IN ('public', 'internal', 'restricted'))
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "entries" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"category" text NOT NULL,
	"tags" text[] DEFAULT '{}'::text[] NOT NULL,
	"body" text NOT NULL,
	"source_pointer" text NOT NULL,
	"last_verified_at" timestamp with time zone NOT NULL,
	"sensitivity" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "entries_id_sensitivity_uq" UNIQUE("id","sensitivity"),
	CONSTRAINT "entries_sensitivity_check" CHECK ("entries"."sensitivity" IN ('public', 'internal', 'restricted'))
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "entries_versions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"entry_id" uuid NOT NULL,
	"version_no" integer NOT NULL,
	"title" text NOT NULL,
	"category" text NOT NULL,
	"tags" text[] DEFAULT '{}'::text[] NOT NULL,
	"body" text NOT NULL,
	"sensitivity" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "entries_versions_entry_id_version_no_uq" UNIQUE("entry_id","version_no"),
	CONSTRAINT "entries_versions_sensitivity_check" CHECK ("entries_versions"."sensitivity" IN ('public', 'internal', 'restricted'))
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "audit_log" ADD CONSTRAINT "audit_log_entry_id_entries_id_fk" FOREIGN KEY ("entry_id") REFERENCES "public"."entries"("id") ON DELETE restrict ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "chunks" ADD CONSTRAINT "chunks_entry_id_sensitivity_fk" FOREIGN KEY ("entry_id","sensitivity") REFERENCES "public"."entries"("id","sensitivity") ON DELETE cascade ON UPDATE cascade;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "entries_versions" ADD CONSTRAINT "entries_versions_entry_id_entries_id_fk" FOREIGN KEY ("entry_id") REFERENCES "public"."entries"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "chunks_embedding_hnsw_idx" ON "chunks" USING hnsw ("embedding" vector_cosine_ops);
